title: "Loek's Blog"
domain: blog.pipeframe.xyz
exclude:
  - makefile
  - license
  - readme.md
collections:
  items:
    permalink: /post/:title/
    output: true
defaults:
  - scope:
      type: items
    values:
      layout: default
      lang: en
      toc: true
      output: true
      footer: true
markdown: kramdown
sass:
  style: compressed
  sourcemap: development
gems:
  - jekyll-liquify

