title: "Loek's Blog"
domain: blog.pipeframe.xyz
permalink: /post/:title/
exclude:
  - makefile
  - license
  - readme.md
defaults:
  - scope:
      type: posts
    values:
      layout: default
      lang: en
      toc: true
markdown: kramdown
sass:
  style: compressed
  sourcemap: development
gems:
  - jekyll-liquify
nojs-search: https://google.com/search

