title: "Loek's Blog"
rss:
  url: https://blog.pipeframe.xyz/atom.xml
permalink: /post/:title
exclude:
  - makefile
  - license
defaults:
  - scope:
      type: posts
    values:
      layout: post
      lang: en
markdown: kramdown
sass:
  style: compressed
  sourcemap: development
