#!/bin/sh
export LANG=C

file="$1"
tab="$(printf '\t')"

git log \
	--follow \
	--ignore-all-space --diff-filter=AM \
	--date=unix --pretty=format:"%H$tab%cd$tab%an" \
	-- "$file" |\
awk -F"$tab" '
BEGIN { printf("git_log:\n") }
{
	printf("  - hash: \"%s\"\n", $1)
	printf("    date: \"@%s\"\n", $2)
	printf("    author: \"%s\"\n", $3)
}
'

