#!/bin/sh

web_root=/home/loek/gert

cd $(dirname $0)

echo "> generating posts.json..."
./genposts

cd ..

echo "> building static files..."
npx next build

echo "> exporting static files..."
npx next export

echo "> moving static files to $web_root..."
mv out $web_root
