#!/bin/sh

postsmeta=$( find ../posts \
	-name "*.md" \
	-type f \
	-exec ./postinfo {} \; |\
	jq -s '.')

jq -n \
	--argjson valid_tags "$(./tags)" \
	--argjson posts "$postsmeta" \
'{
	"valid_tags": $valid_tags,
	"posts": $posts
}'

